server:
  port: 80

spring:
  main:
    banner-mode: off
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: postgres